# Use Node.js as the base image
FROM node:22-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5050

# Set environment variables
ENV NODE_ENV=production

# Command to run the application
CMD ["npm", "start"]
