name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './**/package-lock.json'

    - name: Debug - List Files
      run: ls -R

    - name: Backend - Install Dependencies
      working-directory: ./backend
      run: npm ci

    - name: Backend - Run Linter
      working-directory: ./backend
      run: npm run lint

    - name: Backend - Run Tests
      working-directory: ./backend
      run: npm test

    - name: Frontend - Install Dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Frontend - Run Linter
      working-directory: ./frontend
      run: npm run lint

    - name: Frontend - Run Tests
      working-directory: ./frontend
      run: npm test

    - name: Frontend - Build
      working-directory: ./frontend
      run: npm run build
